"""
probe_map_widget.py

Interactive Neuropixels probe map, visually and behaviorally inspired by
Phy2 / Kilosort4's channel view.

Design goals (replacing the matplotlib-based ProbeSelector):
  - Single batched ScatterPlotItem for all electrodes instead of one
    Rectangle + one Text per channel -> one draw call instead of ~800.
  - pyqtgraph's ViewBox for GPU-accelerated, truly smooth pan/zoom
    ("infinite zoom" feel), with wheel-zoom-to-cursor like KS4.
  - Hit-testing delegated to pyqtgraph's spatial lookup (pointsAt),
    not a per-frame Python loop over every channel.
  - Level-of-detail: channel number labels only render past a zoom
    threshold and only for currently visible channels.
  - Dark theme, circular markers, shank coloring, subtle depth grid,
    consistent with Phy2/KS4 conventions.

Channel states
--------------
Each electrode is in exactly one of three states, tracked per-index in
self.state:

    0 = active    (default, clickable to select)
    1 = selected  (currently being displayed in the trace view)
    2 = rejected  (explicitly rejected by the user; NOT clickable, and
                   hidden from every downstream consumer: trace view
                   drops it, Phy panel hides its units, focus
                   neighborhoods skip it)

Rejection is driven by a text field in the Probe Map dock, Kilosort-
style: the user types a list like "[19, 66]" and those channels become
rejected; removing them from the list un-rejects them. There is no
per-electrode click gesture for rejection, because the list is the
single authoritative input.

State 2 used to be a softer "excluded" concept that nothing in the app
ever invoked; it has been repurposed as the rejection state since no
callers relied on the old meaning.

This module has NO dependency on matplotlib and no dependency on the
rest of data_explorer other than the plain dict produced by
neuropixels_probe_extractor.extract_probes_from_settings(...)[
    'probes'][<key>] (i.e. a dict with 'coordinates' and 'shanks' keys).

Usage
-----
    from PyQt6.QtWidgets import QApplication
    from data_explorer.gui.probe_map_widget import ProbeMapWidget

    app = QApplication([])
    widget = ProbeMapWidget(probe_data)
    widget.channelsSelected.connect(lambda chans: print("selected:", chans))
    widget.channelsRejectedChanged.connect(lambda chans: print("rejected:", chans))
    widget.show()
    app.exec()
"""

from __future__ import annotations

import numpy as np
import pyqtgraph as pg
from PyQt6.QtCore import Qt, pyqtSignal, QPointF
from PyQt6.QtGui import QColor, QFont, QPen, QBrush
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QLabel, QCheckBox,
    QGraphicsRectItem, QGraphicsEllipseItem, QSlider,
)
import colorsys



# ---------------------------------------------------------------------------
# Visual constants (tuned to look like Phy2 / Kilosort4)
# ---------------------------------------------------------------------------

BG_COLOR = "#1e1e1e"
GRID_COLOR = (255, 255, 255, 18)          # faint white, low alpha
LABEL_COLOR = (210, 210, 210, 200)
LABEL_COLOR = (255, 255, 255, 255)


# ---------------------------------------------------------------------------
# State colors. These are used for electrode *state* (selected / rejected /
# hovered / default single-shank), and must never appear in SHANK_PALETTE:
# an electrode is either state-colored or shank-colored, but both kinds can
# be on screen at once, and a shank color identical to a state color would
# make the two indistinguishable to the eye.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# State colors (reserved; never appear in a generated shank palette).
# ---------------------------------------------------------------------------
COLOR_ACTIVE = QColor("#3a86ff")          # default, single-shank only
COLOR_SELECTED = QColor("#42d77d")        # selected for viewing
COLOR_REJECTED = QColor("#2e2e2e")        # rejected; dim, inert
COLOR_HOVER_RING = QColor("#ffd23f")      # hover halo


# Curated qualitative palette for the first shanks, hand-picked to be
# perceptually distinct from each other and from the reserved state
# colors above. Deliberately excludes green (COLOR_SELECTED), yellow
# (COLOR_HOVER_RING), and near-black (COLOR_REJECTED).
_SHANK_PALETTE_HEAD = [
    "#4c8dff",  # blue
    "#e05252",  # red
    "#ff8c42",  # orange
    "#b57bff",  # purple
    "#3fb8c4",  # teal
    "#e56bb5",  # pink
    "#c77d3a",  # brown
    "#7f9cd6",  # steel blue
    "#d97941",  # rust
    "#9b8dcf",  # lavender
]


def _generate_shank_palette(n: int) -> list[QColor]:
    """Return a list of `n` distinct QColors for shanks.

    The first len(_SHANK_PALETTE_HEAD) shanks use the curated list
    (visually separated, hand-checked against the reserved state
    colors). Beyond that, additional colors are generated by evenly
    spacing hues around the HSV wheel while holding saturation and
    value fixed, so every generated color is as vivid as the head.
    Hues near the reserved green and yellow bands are skipped, since
    those would be visually confusable with selected / hover state.

    Deterministic: the same n always produces the same list, so a
    probe's shanks look the same across sessions.
    """
    n = max(1, int(n))
    head_len = len(_SHANK_PALETTE_HEAD)

    if n <= head_len:
        return [QColor(h) for h in _SHANK_PALETTE_HEAD[:n]]

    palette = [QColor(h) for h in _SHANK_PALETTE_HEAD]
    extra_needed = n - head_len

    # Hue bands to avoid (degrees, [start, end)). Green ~ 120, yellow
    # ~ 60. Reserved for COLOR_SELECTED and COLOR_HOVER_RING
    # respectively; a generated shank color in either band would be
    # ambiguous with a state color.
    # We also avoid the immediate neighbours (cyan-ish and orange-ish)
    # to keep a safety margin.
    avoid_bands = [
        (45, 75),    # yellow / gold
        (105, 145),  # green
    ]

    def hue_is_ok(deg: float) -> bool:
        for lo, hi in avoid_bands:
            if lo <= deg < hi:
                return False
        return True

    # Walk the hue circle and collect acceptable hues until we have
    # extra_needed of them. Step size is chosen so we produce *at
    # least* extra_needed samples; we may produce more and truncate.
    # The golden-ratio stride (~137.5°) gives well-spread hues without
    # clustering, which matters when the total count is large.
    golden = 137.507764
    hue = 200.0     # start on the blue side, away from both avoided bands
    generated: list[QColor] = []
    max_iters = extra_needed * 20 + 100  # safety bound

    for _ in range(max_iters):
        if len(generated) >= extra_needed:
            break
        if hue_is_ok(hue % 360.0):
            # colorsys.hsv_to_rgb wants H, S, V in [0, 1].
            r, g, b = colorsys.hsv_to_rgb(
                (hue % 360.0) / 360.0, 0.62, 0.95
            )
            generated.append(QColor(int(r * 255), int(g * 255), int(b * 255)))
        hue += golden

    # If the golden stride didn't fill the quota (shouldn't happen at
    # realistic counts, but be safe), fall back to a linear sweep.
    if len(generated) < extra_needed:
        for i in range(extra_needed - len(generated)):
            hue = (i * 360.0 / max(1, extra_needed)) % 360.0
            r, g, b = colorsys.hsv_to_rgb(hue / 360.0, 0.62, 0.95)
            generated.append(QColor(int(r * 255), int(g * 255), int(b * 255)))

    palette.extend(generated[:extra_needed])
    return palette

MIN_LABEL_SPACING_PX = 4  # only draw channel-number text once neighboring
                            # electrodes are at least this far apart on
                            # screen -- calibrated against actual electrode
                            # pitch (see _min_electrode_pitch_um), not a
                            # fixed px-per-um constant which breaks across
                            # probes with different geometries.


class ProbeMapWidget(QWidget):
    """
    Interactive probe map: click electrodes to select/deselect, pan/zoom
    freely (mouse drag = pan, wheel = zoom-to-cursor), double-click empty
    space to clear the current selection (mirrors phy2's behavior).

    Emits
    -----
    channelsSelected(list[int])
        Whenever the selection set changes, sorted by depth ascending.
        Never includes rejected channels.
    channelsRejectedChanged(list[int])
        Whenever the rejected set changes.
    """

    channelsSelected = pyqtSignal(list)
    channelsRejectedChanged = pyqtSignal(list)

    def __init__(self, probe_data: dict, parent=None):
        super().__init__(parent)

        coords = probe_data["coordinates"]
        shanks = probe_data.get("shanks", {})



        self.channels = np.asarray(coords["channels"], dtype=np.int64)
        self.xcoords = np.asarray(coords["x"], dtype=np.float64)
        self.ycoords = np.asarray(coords["y"], dtype=np.float64)

        if shanks.get("ids"):
            self.shank_ids = np.asarray(shanks["ids"], dtype=np.int64)
        else:
            self.shank_ids = np.zeros(len(self.channels), dtype=np.int64)

        n_shanks = len(np.unique(self.shank_ids))
        self.shank_palette: list[QColor] = _generate_shank_palette(n_shanks)

        n = len(self.channels)
        # Per-channel state, tracked as arrays (not per-artist attributes)
        self.state = np.zeros(n, dtype=np.uint8)  # 0=active 1=selected 2=rejected
        self._hover_idx: int | None = None

        # channel -> row index, for O(1) lookups
        self._chan_to_idx = {int(ch): i for i, ch in enumerate(self.channels)}

        self._min_pitch_um = self._min_electrode_pitch_um()
        self.base_font_size = 9  # Default label size

        self.setMinimumSize(400, 600)

        self._build_ui()
        self._build_scatter()
        self._update_colors()
        self._auto_range()

    def _min_electrode_pitch_um(self) -> float:
        """Smallest center-to-center distance between any two electrodes,
        used to decide when they're visually 'resolvable' enough to label."""
        if len(self.ycoords) < 2:
            return 20.0
        uy = np.unique(self.ycoords)
        if len(uy) < 2:
            return 20.0
        return float(np.min(np.diff(np.sort(uy))))

    # ------------------------------------------------------------------
    # UI scaffolding
    # ------------------------------------------------------------------

    def _build_ui(self):
        pg.setConfigOption("background", BG_COLOR)
        pg.setConfigOption("foreground", "#d0d0d0")
        pg.setConfigOption("antialias", True)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(4, 4, 4, 4)
        layout.setSpacing(4)

        # ---- top bar: counts + actions (thin, phy2-style) ----
        bar = QHBoxLayout()
        self.status_label = QLabel()
        self.status_label.setStyleSheet("color: #b0b0b0; font-size: 11px;")
        bar.addWidget(self.status_label)
        bar.addStretch(1)

        self.labels_checkbox = QCheckBox("Labels")
        self.labels_checkbox.setChecked(True)
        self.labels_checkbox.stateChanged.connect(self._on_toggle_labels)
        bar.addWidget(self.labels_checkbox)

        btn_select_all = QPushButton("Select All")
        btn_select_all.clicked.connect(self.select_all)
        bar.addWidget(btn_select_all)

        btn_clear = QPushButton("Clear")
        btn_clear.clicked.connect(self.clear_selection)
        bar.addWidget(btn_clear)

        layout.addLayout(bar)

        # ---- Size control bar ----
        size_bar = QHBoxLayout()
        size_bar.addWidget(QLabel("Point Size:"))

        # Point size slider
        self.size_slider = QSlider(Qt.Orientation.Horizontal)
        self.size_slider.setMinimum(4)
        self.size_slider.setMaximum(50)
        self.size_slider.setValue(14)  # Default value
        self.size_slider.setTickInterval(2)
        self.size_slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.size_slider.setFixedWidth(150)
        self.size_slider.valueChanged.connect(self._on_size_changed)
        size_bar.addWidget(self.size_slider)

        # Size value display
        self.size_label = QLabel("14")
        self.size_label.setStyleSheet("color: #b0b0b0; font-size: 11px; min-width: 20px;")
        size_bar.addWidget(self.size_label)
        size_bar.addStretch(1)

        layout.addLayout(size_bar)

        # ---- Label size control bar ----
        label_size_bar = QHBoxLayout()
        label_size_bar.addWidget(QLabel("Label Size:"))

        self.label_size_slider = QSlider(Qt.Orientation.Horizontal)
        self.label_size_slider.setMinimum(4)
        self.label_size_slider.setMaximum(50)
        self.label_size_slider.setValue(9)  # Default
        self.label_size_slider.setTickInterval(2)
        self.label_size_slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.label_size_slider.setFixedWidth(150)
        self.label_size_slider.valueChanged.connect(self._on_label_size_changed)
        label_size_bar.addWidget(self.label_size_slider)

        self.label_size_label = QLabel("9")
        self.label_size_label.setStyleSheet("color: #b0b0b0; font-size: 11px; min-width: 20px;")
        label_size_bar.addWidget(self.label_size_label)
        label_size_bar.addStretch(1)

        layout.addLayout(label_size_bar)

        # ---- main plot area ----
        self.plot_widget = pg.PlotWidget()
        self.plot_widget.setAspectLocked(True)          # true physical aspect, phy2-style
        self.plot_widget.showGrid(x=True, y=True)
        self.plot_widget.setMenuEnabled(False)
        self.plot_widget.hideButtons()
        self.plot_widget.setLabel("bottom", "X", units="\u00b5m")
        self.plot_widget.setLabel("left", "Depth", units="\u00b5m")

        self.view_box = self.plot_widget.getViewBox()
        self.view_box.setMouseMode(pg.ViewBox.PanMode)
        # Wheel zoom already zooms to cursor by default in pyqtgraph.

        layout.addWidget(self.plot_widget, stretch=1)

        # Depth gridlines drawn manually (thin horizontal lines every
        # unique y) so they stay visually subordinate to the electrodes,
        # matching KS4's faint horizontal reference lines.
        self._draw_depth_grid()

        # Mouse interaction
        self.plot_widget.scene().sigMouseClicked.connect(self._on_mouse_clicked)
        self.plot_widget.scene().sigMouseMoved.connect(self._on_mouse_moved)

        self._update_status()

    def _on_label_size_changed(self, value):
        """Update label base size when slider changes."""
        self.label_size_label.setText(str(value))
        self.base_font_size = value
        self._update_label_visibility()

    def _on_size_changed(self, value):
        """Update marker size when slider changes."""
        self.size_label.setText(str(value))
        self.scatter.setSize(value)

    def _draw_depth_grid(self):
        unique_y = np.unique(self.ycoords)
        # Thin out if there are a huge number of rows (e.g. dense NP2 probes)
        max_lines = 60
        if len(unique_y) > max_lines:
            step = max(1, len(unique_y) // max_lines)
            unique_y = unique_y[::step]

        pen = pg.mkPen(color=GRID_COLOR, width=1)
        x_min, x_max = self.xcoords.min() - 40, self.xcoords.max() + 40
        for y in unique_y:
            line = pg.PlotCurveItem(
                x=[x_min, x_max], y=[y, y], pen=pen
            )
            line.setZValue(-10)
            self.plot_widget.addItem(line)

    # ------------------------------------------------------------------
    # Scatter (electrodes) — single batched item
    # ------------------------------------------------------------------

    def _build_scatter(self):
        initial_size = self._marker_size_px()
        self.scatter = pg.ScatterPlotItem(
            x=self.xcoords,
            y=self.ycoords,
            size=initial_size,
            pxMode=True,
            symbol="o",
            pen=pg.mkPen(None),
            brush=pg.mkBrush(COLOR_ACTIVE),
            hoverable=False,
        )

        self.scatter.setZValue(10)
        self.plot_widget.addItem(self.scatter)

        # Text labels: created lazily/hidden, one pg.TextItem per channel
        # is still ~800 objects, but they are only made *visible* (and thus
        # only cost paint time) when zoomed in and in view -- see
        # _update_label_visibility. This matches phy2's LOD behavior.
        self._label_items: list[pg.TextItem | None] = [None] * len(self.channels)
        self.view_box.sigRangeChanged.connect(self._on_range_changed)

    def _marker_size_px(self) -> float:
        # Use slider value if available, otherwise default
        if hasattr(self, 'size_slider'):
            return float(self.size_slider.value())
        return 14.0  # Default fallback

    # ------------------------------------------------------------------
    # Color / state updates (batched — no per-artist mutation)
    # ------------------------------------------------------------------

    def _update_colors(self):
        has_multi_shank = len(np.unique(self.shank_ids)) > 1
        brushes = []
        pens = []
        for i in range(len(self.channels)):
            st = self.state[i]
            if st == 2:
                # Rejected: dim, inert. Deliberately checked first so a
                # rejected channel never gets shank-colored or hover-
                # ringed.
                color = COLOR_REJECTED
            elif st == 1:
                color = COLOR_SELECTED
            elif has_multi_shank:
                color = self.shank_palette[int(self.shank_ids[i]) % len(self.shank_palette)]
            else:
                color = COLOR_ACTIVE

            if i == self._hover_idx and st != 2:
                pens.append(pg.mkPen(COLOR_HOVER_RING, width=2))
            else:
                pens.append(pg.mkPen(None))
            brushes.append(pg.mkBrush(color))

        self.scatter.setBrush(brushes)
        self.scatter.setPen(pens)
        self._update_status()

    def _update_status(self):
        n_sel = int(np.sum(self.state == 1))
        n_rej = int(np.sum(self.state == 2))
        total = len(self.channels)
        self.status_label.setText(
            f"{n_sel} selected  \u00b7  {n_rej} rejected  \u00b7  {total} total"
        )

    # ------------------------------------------------------------------
    # Interaction: click to select/deselect
    # ------------------------------------------------------------------

    def _on_mouse_clicked(self, ev):
        # Only handle left clicks.
        if ev.button() != Qt.MouseButton.LeftButton:
            return

        if self._hover_idx is None:
            return

        idx = self._hover_idx

        # Rejected channels are inert: no state change on left-click.
        # Rejection is undone by removing the channel from the list in
        # the Probe Map dock, not by clicking.
        if self.state[idx] == 2:
            ev.accept()
            return

        if self.state[idx] == 1:
            self.state[idx] = 0
        else:
            self.state[idx] = 1

        self._update_colors()
        self._emit_selection()
        ev.accept()

    def _on_scatter_hovered(self, plot_item, points, ev):
        if points is not None and hasattr(points, 'size') and points.size > 0:
            new_hover = points[0].index()
        else:
            new_hover = None

        if new_hover != self._hover_idx:
            self._hover_idx = new_hover
            self._update_colors()

    def _on_mouse_moved(self, scene_pos):
        if not self.plot_widget.sceneBoundingRect().contains(scene_pos):
            return

        points_at = self.scatter.pointsAt(
            self.view_box.mapSceneToView(scene_pos)
        )
        self._on_scatter_hovered(self.scatter, points_at, None)

    def _emit_selection(self):
        selected_channels = self.channels[self.state == 1]
        order = np.argsort(self.ycoords[self.state == 1])
        selected_sorted = selected_channels[order].tolist()
        self.channelsSelected.emit(selected_sorted)

    def _emit_rejected(self):
        rejected = self.channels[self.state == 2].tolist()
        self.channelsRejectedChanged.emit(rejected)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def set_selected_channels(self, channel_list):
        """Select exactly the given channels (replacing any current
        selection). Rejected channels are left rejected and are never
        added to the selection, even if present in `channel_list`."""
        wanted = set(int(c) for c in channel_list)
        for ch, idx in self._chan_to_idx.items():
            if self.state[idx] == 2:   # leave rejected channels alone
                continue
            self.state[idx] = 1 if ch in wanted else 0
        self._update_colors()
        self._emit_selection()

    def set_rejected(self, channel_list):
        """Set the rejected set to exactly `channel_list`. Channels
        entering the rejected set are also removed from the selection,
        so the two signals stay consistent."""
        wanted = set(int(c) for c in channel_list)
        selection_changed = False
        rejected_changed = False

        for ch, idx in self._chan_to_idx.items():
            currently_rejected = (self.state[idx] == 2)
            should_be_rejected = ch in wanted

            if should_be_rejected and not currently_rejected:
                # Entering rejection: also drop from selection if there.
                self.state[idx] = 2
                rejected_changed = True
                selection_changed = True   # a selected channel may have been removed
            elif not should_be_rejected and currently_rejected:
                # Leaving rejection: back to plain active.
                self.state[idx] = 0
                rejected_changed = True
            # else: unchanged.

        self._update_colors()
        if rejected_changed:
            self._emit_rejected()
        if selection_changed:
            self._emit_selection()

    def get_rejected_channels(self) -> list[int]:
        return self.channels[self.state == 2].tolist()

    def select_all(self):
        """Select every non-rejected channel."""
        self.state[self.state != 2] = 1
        self._update_colors()
        self._emit_selection()

    def clear_selection(self):
        self.state[self.state == 1] = 0
        self._update_colors()
        self._emit_selection()

    def get_selected_channels(self) -> list[int]:
        selected_channels = self.channels[self.state == 1]
        order = np.argsort(self.ycoords[self.state == 1])
        return selected_channels[order].tolist()

    # ------------------------------------------------------------------
    # Level-of-detail labels + view range handling
    # ------------------------------------------------------------------

    def _on_range_changed(self, *_):
        self._update_label_visibility()

    def _update_label_visibility(self):
        (x0, x1), (y0, y1) = self.view_box.viewRange()
        view_height_um = max(y1 - y0, 1e-6)

        # Use slider value for base font size
        base_font_size = self.base_font_size if hasattr(self, 'base_font_size') else 9
        reference_height = 500
        zoom_factor = max(0.5, min(3.0, reference_height / view_height_um))

        # Get max from slider if available
        max_label_size = self.label_size_slider.maximum() if hasattr(self, 'label_size_slider') else 30
        font_size = max(4, min(max_label_size, base_font_size * zoom_factor))

        show_labels = self.labels_checkbox.isChecked()

        if not show_labels:
            for item in self._label_items:
                if item is not None:
                    item.setVisible(False)
            return

        visible_mask = (
            (self.xcoords >= x0) & (self.xcoords <= x1)
            & (self.ycoords >= y0) & (self.ycoords <= y1)
        )
        visible_idx = np.where(visible_mask)[0]

        MAX_LABELS = 800  # Increased to show all 384 channels
        if len(visible_idx) > MAX_LABELS:
            visible_idx = visible_idx[:MAX_LABELS]

        visible_set = set(visible_idx.tolist())

        for i in range(len(self.channels)):
            want_visible = i in visible_set
            item = self._label_items[i]

            if want_visible and item is None:
                item = pg.TextItem(
                    text=str(int(self.channels[i])),
                    color=LABEL_COLOR,
                    anchor=(0.5, 0.5),
                )
                font = QFont()
                font.setPointSizeF(font_size)
                font.setBold(True)
                item.setFont(font)
                item.setPos(self.xcoords[i], self.ycoords[i])
                item.setZValue(20)
                self.plot_widget.addItem(item)
                self._label_items[i] = item

            elif item is not None:
                item.setVisible(want_visible)
                if want_visible:
                    new_font = QFont()
                    new_font.setPointSizeF(font_size)
                    new_font.setBold(True)
                    item.setFont(new_font)
                    item.setColor(QColor(255, 255, 255, 255))

    def _on_toggle_labels(self, _state):
        self._update_label_visibility()

    def _auto_range(self):
        pad_x = max((self.xcoords.max() - self.xcoords.min()) * 0.15, 30)
        pad_y = max((self.ycoords.max() - self.ycoords.min()) * 0.03, 30)
        self.view_box.setRange(
            xRange=(self.xcoords.min() - pad_x, self.xcoords.max() + pad_x),
            yRange=(self.ycoords.min() - pad_y, self.ycoords.max() + pad_y),
            padding=0,
        )